### PR TITLE
Add self-check of test system, simplify and document setup process

### PR DESCRIPTION
**Pull request by martinling**
This PR makes a number of improvements to simplify setting up and troubleshooting a Tycho test station:
- Adds a self-check of the test setup which is run on startup, and can be run individually with `make check`. This checks:
    -  GreatFET detected with correct firmware version.
    - Black Magic Probe detected with correct firmware version.
    - DC-DC converter detected and operating.
    - 24V supply detected.
- Adds a udev rules file which can be installed with `make install-udev`.
- Adds a Black Magic Probe firmware image which can be flashed with `make flash-blackmagic`.
- Autodetects the correct serial port to use for the Black Magic Probe.
- Moves check for the Target-A cable earlier in the test to detect an erroneous setup earlier.
- Updates README with hardware requirements, assembly instructions and software steps.

### CODE REVIEW

**Comment by mossmann** [comment]
This looks fantastic, but I'll refrain from a full review since I don't currently have hardware to test it.

**Review by grvvy — COMMENTED** [review]
Test passed!

A few caveats:
* It sometimes throws `FAIL: TARGET-A cable appears to be connected, should be disconnected` when the cable isn't connected. Subsequent runs of the test usually don't fail here again; could be cable quality related?
* Needed to `pip install pyyaml` globally or outside of the venv but that is listed in the greatfet prerequisites to be fair.
* Permission denied at `make flash-blackmagic` but mine was already `1.9.1` so it passed the check.

**Comment by martinling** [comment]
@grvvy 

> It sometimes throws `FAIL: TARGET-A cable appears to be connected, should be disconnected` when the cable isn't connected. Subsequent runs of the test usually don't fail here again; could be cable quality related?

Shouldn't be cable quality related. This check only uses VBUS/GND at extremely low current. It's not trying to send anything over the data lines.

It sounds like there may be some residual voltage lurking on `TARGET_A_VBUS`. We may need to use the discharge resistor to drain it before applying the pullup and running the test. I'll try to reproduce the issue here and see if that fixes it.

> Needed to `pip install pyyaml` globally or outside of the venv but that is listed in the greatfet prerequisites to be fair.

Good catch.

This is currently needed when you run `flash-greatfet`, because the `Makefile` specifies that `greatfet_usb.bin` depends on the copy built in `dependencies/greatfet/firmware/build/greatfet_usb/greatfet_usb.bin`, so if you haven't previously built that, it tries to build it, and that build process uses the system's Python rather than the one in the venv.

But I think what we want is for it to just flash the `greatfet_usb.bin` that's already sitting there. Otherwise it's not just `pyyaml` that's the issue, you also need the whole ARM embedded toolchain.

I've pushed a commit that fixes this such that `make flash-greatfet` uses the existing `greatfet_usb.bin`. To rebuild that file you would use `make greatfet-firmware` instead.

> Permission denied at `make flash-blackmagic` but mine was already `1.9.1` so it passed the check.

You need a udev rule that allows access to the BMP in DFU mode, in which state it has product ID 0x6017 rather than 0x6018. This is included in `60-tycho.rules`. Did you run `make install-udev` or were you relying on rules you'd set up previously?

**Comment by grvvy** [comment]
@martinling 

> I've pushed a commit that fixes this such that make flash-greatfet uses the existing greatfet_usb.bin. To rebuild that file you would use make greatfet-firmware instead.

Nice!

> You need a udev rule that allows access to the BMP in DFU mode, in which state it has product ID 0x6017 rather than 0x6018. This is included in 60-tycho.rules. Did you run make install-udev or were you relying on rules you'd set up previously?

Ah I thought I'd reloaded my rules after installing them but must not have. I get a pipe error now when running `make flash-blackmagic`

**Comment by martinling** [comment]
@grvvy 

> Ah I thought I'd reloaded my rules after installing them but must not have. I get a pipe error now when running `make flash-blackmagic`

I have no idea what that's about. Can you post the output? Does flashing the BMP using `dfu-util` instead work? I made it use `fwup-util` since we already have that installed in the environment, but it was the first time I'd tried that tool on a BMP I think. Perhaps your unit has a different bootloader version it doesn't like. Pipe error usually indicates a STALL response to a USB request.

**Comment by martinling** [comment]
I've just managed to reproduce the pipe error by accident, after repeatedly failing to do so deliberately. It happens when the BMP is _not_ in DFU mode. To flash firmware to the BMP you need to put it into DFU mode, by reconnecting it whilst holding the 'B' button.

**Comment by martinling** [comment]
I wasn't able to reproduce the false positive on the Target-A cable check, but I did see the measured voltage get fairly close to the 0.05V threshold, so I have increased the threshold to 0.1V. Give it a try and see if that works better for you.

**Comment by grvvy** [comment]
> I wasn't able to reproduce the false positive on the Target-A cable check, but I did see the measured voltage get fairly close to the 0.05V threshold, so I have increased the threshold to 0.1V. Give it a try and see if that works better for you.

This seems like it did the trick. I've run the test a dozen times and haven't gotten it again.

The only one-off errors that have occurred in this session are
```
• Flashing Apollo to MCU via DFU... FAIL

FAIL: Command 'environment/bin/fwup-util -d 1d50:615c firmware.bin' failed with exit status 64768
```
and
```
  • Testing USB HS comms on AUX:
    • Connecting host D+/D- to AUX

FAIL: [Errno 5] Input/Output Error
```
both happened only once.

> I've just managed to reproduce the pipe error by accident, after repeatedly failing to do so deliberately. It happens when the BMP is _not_ in DFU mode. To flash firmware to the BMP you need to put it into DFU mode, by reconnecting it whilst holding the 'B' button.

Woops! Trying it in DFU mode finds the device and tries programming it but ends in a timeout
```
$ make flash-blackmagic
environment/bin/fwup-util blackmagic.bin

Target found!
Programming 109404 bytes...
Traceback (most recent call last):                                              
  File "/home/grvvy/repos/cynthion-test-upstream/cynthion-test/environment/bin/fwup-util", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/grvvy/repos/cynthion-test-upstream/cynthion-test/dependencies/pyfwup/fwup_utils/fwup_util.py", line 124, in main
    board.program(program_data, status_callback = lambda written, _ : progress.update(written))
  File "/home/grvvy/repos/cynthion-test-upstream/cynthion-test/dependencies/pyfwup/fwup/dfu.py", line 263, in program
    self.__raw_write_page(page_address, data_to_program)
  File "/home/grvvy/repos/cynthion-test-upstream/cynthion-test/dependencies/pyfwup/fwup/dfu.py", line 236, in __raw_write_page
    self.__complete_command()
  File "/home/grvvy/repos/cynthion-test-upstream/cynthion-test/dependencies/pyfwup/fwup/dfu.py", line 204, in __complete_command
    status, poll_timeout, state = self.__get_status()
                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/grvvy/repos/cynthion-test-upstream/cynthion-test/dependencies/pyfwup/fwup/dfu.py", line 191, in __get_status
    raw_status = self.__dfu_in_request(self.DFU_GET_STATUS, 0, self.DFU_STATUS_LENGTH)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grvvy/repos/cynthion-test-upstream/cynthion-test/dependencies/pyfwup/fwup/dfu.py", line 183, in __dfu_in_request
    return self.device.ctrl_transfer(self.USB_CLASS_IN_REQUEST_TO_INTERFACE, request, value,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grvvy/repos/cynthion-test-upstream/cynthion-test/environment/lib/python3.11/site-packages/usb/core.py", line 1082, in ctrl_transfer
    ret = self._ctx.backend.ctrl_transfer(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grvvy/repos/cynthion-test-upstream/cynthion-test/environment/lib/python3.11/site-packages/usb/backend/libusb1.py", line 893, in ctrl_transfer
    ret = _check(self.lib.libusb_control_transfer(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grvvy/repos/cynthion-test-upstream/cynthion-test/environment/lib/python3.11/site-packages/usb/backend/libusb1.py", line 602, in _check
    raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBTimeoutError: [Errno 110] Operation timed out
make: *** [Makefile:34: flash-blackmagic] Error 1
```

**Comment by martinling** [comment]
> ```
> • Flashing Apollo to MCU via DFU... FAIL
> 
> FAIL: Command 'environment/bin/fwup-util -d 1d50:615c firmware.bin' failed with exit status 64768
> ```

I don't know what the cause of this was,and the exit status isn't sufficient to debug it. But I have updated the `run_command` function to make it capture the command output and display it as part of the failure message, so if this happens again it should be possible to see what went wrong now.

> ```
>   • Testing USB HS comms on AUX:
>     • Connecting host D+/D- to AUX
> 
> FAIL: [Errno 5] Input/Output Error
> ```

Should be fixed by dcf6776. This intermittent error is caused by the GreatFET glitching off the bus when we switch power to the EUT ports. Disconnecting the host D+/D- from the EUT before flipping the VBUS switches has stopped this happening for me. I've also fixed some other intermittent issues with the speed test.

> ```
> $ make flash-blackmagic
> environment/bin/fwup-util blackmagic.bin
> [...]
> usb.core.USBTimeoutError: [Errno 110] Operation timed out
> make: *** [Makefile:34: flash-blackmagic] Error 1
> ```

I've changed `make flash-blackmagic` to use `dfu-util` instead. This also has the advantage that it knows how to request the BMP to switch from normal to DFU mode, so I've removed the note in the README telling you to put it in DFU mode first. Doing so wasn't actually necessary for `make flash-greatfet` either, since it calls `greatfet_firmware` which knows how to do the same thing.

**Comment by martinling** [comment]
@mossmann I've also added fixes for some further issues you found during bringup:
- [Allow for tolerance in the Tycho load resistors.](https://github.com/greatscottgadgets/cynthion-test/pull/4/commits/d16239f44548bcdfc68edfef3cb642f40400e6c4)
- [Fix missing TARGET_PHY_1V8 test.](https://github.com/greatscottgadgets/cynthion-test/pull/4/commits/2476bf42440a8c76260397644e7cbc5e9a52f942)
- [Use brighter text when requesting user actions.](https://github.com/greatscottgadgets/cynthion-test/pull/4/commits/f6a695b1008abe73a2b0b02c2ffe5735f5ebab9b)

**Review by grvvy — APPROVED** [review]

**Pull request merged**
